"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [input, setInput] = useState("");

  // const navLinks = [
  //   { href: "/", label: "Home" },
  //   { href: "/login", label: "Login" },
  //   { href: "/register", label: "Register" },
  //   { href: "/forgot-password", label: "Forgot Password" },
  // ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <input value={input} onChange={(e) => setInput(e.target.value)} className="border p-2 m-4" placeholder="Type..." />
        </div>
        <div className="container mx-auto px-4">
          <header className="py-4 bg-gray-800 text-white text-center">
            <h1 className="text-3xl font-bold">My Next.js App</h1>
          </header>
         
      
        {children}
        <div className="bg-gray-800 py-4 ">
          <p className="text-center">Additional auth footer can go here.</p>
        </div>
        </div>
      </body>
    </html>
  );
}
